### ISSUE TITLE
✖ 404 The model `gpt-4o` does not exist or you do not have access to it.

### ISSUE THREAD

**Issue by bHARATHaALETI018** [BuilderIO/micro-agent#34]

**Comment by ike5** [comment]
To add to your opened issue, here's the error message I received along with it: 

`✖ 404 The model `gpt-4o` does not exist or you do not have access to it.
    at APIError.generate (file:///Users/ike/.nvm/versions/node/v20.13.1/lib/node_modules/@builder.io/micro-agent/node_modules/openai/error.mjs:50:20)
    at OpenAI.makeStatusError (file:///Users/ike/.nvm/versions/node/v20.13.1/lib/node_modules/@builder.io/micro-agent/node_modules/openai/core.mjs:268:25)
    at OpenAI.makeRequest (file:///Users/ike/.nvm/versions/node/v20.13.1/lib/node_modules/@builder.io/micro-agent/node_modules/openai/core.mjs:311:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getFileSuggestion (file:///Users/ike/.nvm/versions/node/v20.13.1/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:904:22)
    at async interactiveMode (file:///Users/ike/.nvm/versions/node/v20.13.1/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:671:33)
    at async file:///Users/ike/.nvm/versions/node/v20.13.1/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1663:11

    ai-shell v0.0.48

    Please open a Bug report with the information above:
    https://github.com/BuilderIO/micro-agent/issues/new
■  Canceled`

**Comment by steve8708** [comment]
oh wow, I thought gpt-4o was avaiable to nearly everyone now

claude's 3.5 sonnet just came out and is likely better and faster (and is cheaper too). I would recommend trying that

create an account with anthropic and add your key using `micro-agent config` and set `claude` as your model, either through the config or like

```
MODEL=claude micro-agent
```

**Comment by sainsw** [comment]
I think you need to be in at least Tier 1 in OpenAI to access gpt-4o via API

Check your tier here: [https://platform.openai.com/docs/guides/rate-limits/usage-tiers](https://platform.openai.com/settings/organization/limits)

Documentation on the tiers:  [https://platform.openai.com/docs/guides/rate-limits/usage-tiers](https://platform.openai.com/docs/guides/rate-limits/usage-tiers)

**Comment by ike5** [comment]
![limits](https://github.com/BuilderIO/micro-agent/assets/31159328/0baa045c-aae3-4f6c-b2b6-68e4ac0796b4)
You're right, it appears that I haven't met their $5 spending quota yet.

**Comment by Sudococommunity** [comment]
how to use ollama in microagent

**Comment by EzraWolf** [comment]
I am not sure when or why they released tiers, and I haven't spent more than $10 on OpenAI's API, but have tier 3.

What fixed this for me was running `micro-agent config set MODEL=gpt-4o` with the lowercase `gpt-4o`

**Comment by kasm-sayn** [comment]
i spent $27, but I still couldn't get to tier 1
