### ISSUE TITLE
 500 model requires more system memory (14.4 GiB) than is available (12.3 GiB)

### ISSUE THREAD

**Issue by yucelz** [BuilderIO/micro-agent#59]
I was using llama codestral model in the background.

OS VERSION:
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble

AI MODEL
NAME            	        ID          	SIZE 	MODIFIED       
codestral:latest	XXXX	12 GB	
 
version:    micro-agent v0.1.4 

Exception:
 at APIError.generate (file:///usr/lib/node_modules/@builder.io/micro-agent/node_modules/openai/error.mjs:62:20)
    at OpenAI.makeStatusError (file:///usr/lib/node_modules/@builder.io/micro-agent/node_modules/openai/core.mjs:268:25)
    at OpenAI.makeRequest (file:///usr/lib/node_modules/@builder.io/micro-agent/node_modules/openai/core.mjs:311:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getSimpleCompletion (file:///usr/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1055:22)
    at async getFileSuggestion (file:///usr/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:954:9)
    at async interactiveMode (file:///usr/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:735:33)
    at async file:///usr/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1776:11

**Comment by codecrypt112** [comment]
The issue is because you had insufficient amount of memory in your system. Try to free them or extend your memory (RAM or GPU).
