### ISSUE TITLE
attempts to read from non-existent file when environment is in bad state

### ISSUE THREAD

**Issue by emmahyde** [BuilderIO/micro-agent#60]
```fish
╰─❯ micro-agent $TEST_FILENAME -t "bundle exec m"
┌  🦾 Micro Agent
│
◇  Running tests...
Migrations are pending. To resolve this issue, run:
│
│           bin/rails db:migrate RAILS_ENV=test
│
│   You have 1 pending migration:
│
│   20240809185934_add_states_to_gloria_requests.rb
│   Shutting down Karafka producer...
│
│
◇  Generating code...

✖ ENOENT: no such file or directory, open ''
    at async open (node:internal/fs/promises:636:25)
    at async readFile (node:internal/fs/promises:1246:14)
    at async generate (file:///Users/emmahyde/.local/share/nvm/v20.14.0/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1184:20)
    at async runOne (file:///Users/emmahyde/.local/share/nvm/v20.14.0/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1516:34)
    at async run (file:///Users/emmahyde/.local/share/nvm/v20.14.0/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1555:20)
    at async runAll (file:///Users/emmahyde/.local/share/nvm/v20.14.0/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1596:20)
    at async file:///Users/emmahyde/.local/share/nvm/v20.14.0/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1780:7

    micro-agent v0.1.4
```

**Comment by GodBlessSakura** [comment]
Hi, I encountered the same error as below when using micro-agent:
`✖ ENOENT: no such file or directory, open ''
    at async open (node:internal/fs/promises:640:25)
    ...`
Have you managed to solve this issue?
If so, could you please share how you fixed it?
Thank you very much!
