### ISSUE TITLE
how do i fix

### ISSUE THREAD

**Issue by finnisher900** [BuilderIO/micro-agent#64]
✖ ENOENT: no such file or directory, open ''
    at async open (node:internal/fs/promises:638:25)
    at async readFile (node:internal/fs/promises:1238:14)
    at async generate (file:///home/meerkat/.nvm/versions/node/v22.7.0/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1184:20)
    at async runOne (file:///home/meerkat/.nvm/versions/node/v22.7.0/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1516:34)
    at async run (file:///home/meerkat/.nvm/versions/node/v22.7.0/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1555:20)
    at async runAll (file:///home/meerkat/.nvm/versions/node/v22.7.0/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1596:20)
    at async file:///home/meerkat/.nvm/versions/node/v22.7.0/lib/node_modules/@builder.io/micro-agent/dist/cli.mjs:1780:7

**Comment by GodBlessSakura** [comment]
Hi, I encountered the same error as below when using micro-agent:
✖ ENOENT: no such file or directory, open '' at async open (node:internal/fs/promises:640:25) ...
Have you managed to solve this issue?
If so, could you please share how you fixed it?
Thank you very much!
